### ISSUE TITLE
Add more info when failing to parse logs

### ISSUE THREAD

**Issue by ScottESanDiego** [NVIDIA/Bobber#19]
Pointing parse-results to an incorrect log directory (for fun, the test folder) gives a non-intuitive error:

```
dxuser@dgxa100:~$ bobber parse-results /raid/bobber/
Traceback (most recent call last):
  File "/usr/local/bin/bobber", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/bobber/bobber.py", line 337, in main
    execute_command(args, version)
  File "/usr/local/lib/python3.8/dist-packages/bobber/bobber.py", line 310, in execute_command
    parse_results.main(args.log_path, args.compare_baseline)
  File "/usr/local/lib/python3.8/dist-packages/bobber/lib/analysis/parse_results.py", line 115, in main
    bobber_version = check_bobber_version(log_files,
  File "/usr/local/lib/python3.8/dist-packages/bobber/lib/analysis/common.py", line 53, in check_bobber_version
    return version
UnboundLocalError: local variable 'version' referenced before assignment
```

We should catch that, and instead indicate that logs weren't found in that directory.

**Comment by roclark** [comment]
Thanks @ScottESanDiego, great suggestion! I've added this to the roadmap for our next release and will come up with a patch shortly.
