### ISSUE TITLE
Error running all tests

### ISSUE THREAD

**Issue by roclark** [NVIDIA/Bobber#31]
The latest release introduced a bug for a command that should've been removed during a previous update. Now, while attempting to do a `bobber run-all ...` it will return a stacktrace:

```
Traceback (most recent call last):
  File "/mnt/c/Users/robdc/Documents/Bobber/env/bin/bobber", line 8, in <module>
    sys.exit(main())
  File "/mnt/c/Users/robdc/Documents/Bobber/env/lib/python3.8/site-packages/bobber/bobber.py", line 349, in main
    execute_command(args, version)
  File "/mnt/c/Users/robdc/Documents/Bobber/env/lib/python3.8/site-packages/bobber/bobber.py", line 337, in execute_command
    run_tests.test_selector(args, version_underscore)
  File "/mnt/c/Users/robdc/Documents/Bobber/env/lib/python3.8/site-packages/bobber/lib/tests/run_tests.py", line 278, in test_selector
    kickoff_test(args, bobber_version, iteration, args.hosts)
  File "/mnt/c/Users/robdc/Documents/Bobber/env/lib/python3.8/site-packages/bobber/lib/tests/run_tests.py", line 241, in kickoff_test
    elif args.command == RUN_STG_FILL:
NameError: name 'RUN_STG_FILL' is not defined
```

Removing this line of code should handle the situation.

**Comment by roclark** [comment]
Closed with #32
